PREFIX hft:  <http://example.org/hl7-fhir-tool#>

SELECT ?observation WHERE {
    ?observation a hft:Observation ;
                 hft:hasUnit ?u . 
    FILTER (!EXISTS { ?observation hft:valueDecimal ?v } && !EXISTS { ?observation hft:valueInteger ?i } )
}
