PREFIX hft:  <http://example.org/hl7-fhir-tool#>

SELECT ?observation WHERE {
    ?observation a hft:Observation ;
         hft:valueDecimal ?v .
    FILTER NOT EXISTS { ?observation hft:hasUnit ?u }
}